version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123 #Change if needed
      POSTGRES_DB: task_management_db  #database name
    ports:
      - "5432:5432"  # PostgreSQL default port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent data storage

  flask-app:
    build: .
    depends_on:
      - db
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP_SECRET_KEY=supersecretkey123
      - MAIL_USERNAME=example@gmail.com
      - MAIL_PASSWORD=app-specific-password
      - DATABASE_URI=postgresql://user:123@db:5432/task_management_db

volumes:
  postgres_data:
