"""Add subscription table

Revision ID: 130ea7fa6635
Revises: 377579bad61e
Create Date: 2025-01-11 20:12:09.494099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130ea7fa6635'
down_revision = '377579bad61e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('report_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text("'2025-01-01'::date"))
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text("'2025-01-15'::date"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text("'2025-01-15'::date"))
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text("'2025-01-01'::date"))

    op.drop_table('subscriptions')
    # ### end Alembic commands ###
