"""Add fields to tasks

Revision ID: 377579bad61e
Revises: a0d5a1e3177d
Create Date: 2025-01-11 18:14:23.025549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377579bad61e'
down_revision = 'a0d5a1e3177d'
branch_labels = None
depends_on = None


def upgrade():
    # إضافة الأعمدة الجديدة إلى الجدول tasks مع تعيين قيم افتراضية
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False, server_default=sa.text("'2025-01-01'")))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=False, server_default=sa.text("'2025-01-15'")))
        batch_op.add_column(sa.Column('completion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'Pending'")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('completion_date')
        batch_op.drop_column('due_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
